ПР10
ArturKotorin/blog-customizer pull request #1
Opened 2024-07-17 09:15 UTC by ArturKotorin

2024-07-17 10:53 UTC, SergeyK2004 requested changes
Добрый день!  (нужно развернуть комментарий ↓)

У вас получилась отличная работа:
* Полностью реализован функционал.
* Сайдбар закрывается по клику вне сайдбара
* Состояния страницы и формы разделены
* Обработчик события `submit` навешивается на форму, а не на клик по кнопке
* Для условного добавления стилей используется библиотека `clsx`
* Типизированы все пропсы

Но есть пара моментов, который надо поправить:

- https://disk.yandex.ru/d/ss2wKIL6Oslr9A Верстка формы не соответствует макету. Используйте имеющиеся в стартовом наборе компоненты для настройки отступов между полями формы.
- У формы отсутствует заголовок.
- Для дефолтных состояний статьи и формы используется `defaultArticleState`

Правки можно лучше остаются на ваше усмотрение:

- Обычно корневой `index.tsx` держат максимально компактным. Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.
- Обработчик клика по оверлею для закрытия сайдбара лучше попробовать реализовать через кастомный хук.

Успешного рефакторинга!

2024-07-17 10:53 UTC, SergeyK2004 commented on src/components/arrow-button/ArrowButton.tsx
> +			className={clsx(styles.container, {
**Отлично:**

Здорово, что используете библиотеку `clsx`.

2024-07-17 10:53 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	setFormStates: (data: Record<string, OptionType>) => void;
**Можно лучше:**

У вас уже есть тип для объекта с настройками ArticleStateType
Лучше использовать его и в стэйте хранить объект настройками.

2024-07-17 10:53 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const defaultValues = {
**Надо исправить:**

Настройки статьи по умолчанию описаны в объекте `defaultArticleState`  в файле `constants/articleProps.ts` стартеркита. В проекте нужно использовать значения из этого объекта как настройки по умолчанию, как для самой статьи, так и как начальные значения полей форм.
Не допускается использовать для значения по умолчанию элементы с нулевым индексом из массивов свойств. То что настройки по умолчанию имеют именно нулевой индекс можно считать просто совпадением и это может измениться в любой момент.

2024-07-17 10:53 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	useEffect(() => {
**Можно лучше:**

Будет здорово вынести закрытие по клику в оверлей в кастомный хук. Посмотрите, как пример, использование хука в компоненте Select. Только лучше будет использовать событие `mousedown`

2024-07-17 10:53 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +					onSubmit={handleSubmit}
**Отлично:**

Отлично, что обработчик сохранения данных вызывается при отправке формы.

2024-07-17 10:53 UTC, SergeyK2004 commented on src/index.tsx
>  const App = () => {
**Можно лучше:**

Обычно корневой `index.tsx` держат максимально компактным. Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.

2024-07-17 10:53 UTC, SergeyK2004 commented on src/index.tsx
> +		'--font-family': defaultArticleState.fontFamilyOption.value,
**Можно лучше:**

В стейте лучше хранить просто данные - объект со значениями, а стили из данных вычислять отдельно. Такое решение более гибкое и будет полезно, если понадобится передать данные о настройках куда то ещё, например на сервер или сохранить в localStorage

2024-07-18 18:02 UTC, SergeyK2004 requested changes
Отличная работа, большинство недочетов устранены.
Исправьте реализацию отступов между элементами формы и работа будет принята.

2024-07-18 18:02 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.module.scss
> +	gap: 50px;
**Надо исправить:**

Для управления отступами между полями формы нужно использовать компонент Spacing, который был дан вам в стартовом наборе.

2024-07-19 08:59 UTC, ArturKotorin commented on src/components/article-params-form/ArticleParamsForm.module.scss
> +	gap: 50px;
Не понимаю в чем ошибка

2024-07-20 03:07 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.module.scss
> +	gap: 50px;
Артур привет. 
Приходил Максим и внес ясность. К сожалению, стартовый набор, который дан нам, для проверки работ содержит специальный компонент Spacing, с помощью которого реализуются отступы. Без него использование gap не совсем корректно, так как мы можем в форме разместить разные элементы и не обязательно на одинаковом расстоянии. 
![image](https://github.com/user-attachments/assets/be231e56-246f-475a-b1c2-ab42283f6afe)

Но как выяснилось, этот компонент есть у меня, но нет у вас. 🤷‍♂️
Поэтому, приношу свои извинения, но использовать его не получится. Работа принимается.

2024-07-20 03:08 UTC, SergeyK2004 approved these changes
Работа принята. Желаю успехов в дальнейшем обучении.

2024-07-20 09:32 UTC, ArturKotorin commented on src/components/article-params-form/ArticleParamsForm.module.scss
> +	gap: 50px;
А тогда понятно, хорошо что все разъяснилось)

2024-07-20 09:32 UTC, merged